service: image-processing-api

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
        - 's3:PutObject'
        - 'rekognition:DetectLabels'
      Resource:
        - 'arn:aws:s3:::avenga-user-profile-images/*'
        - 'arn:aws:rekognition:*:*:*'

functions:
  imageProcessorFunction:
    handler: handler.process
    events:
      - http:
          path: process
          method: post
          cors:
            origin: '*' # Allow all origins
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
resources:
  Resources:
    S3BucketUserProfileImages:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: avenga-user-profile-images
